apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: arunmarria
    repository: jx-k8s-template
  - key: staging
  - key: production
  ingress:
    domain: afedfdd09ed6b4d2b90b52cf180f0e98-290295559.us-east-1.elb.amazonaws.com
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: arunmarria
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
